# Generated by Django 3.2.9 on 2021-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_auto_20201117_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionbeneficio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoasistencia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
