# Generated by Django 3.2.9 on 2021-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_delete_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadosalud',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
